/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as PoliticaDeReembolsoRouteImport } from './routes/politica-de-reembolso'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as MeusDireitosLgpdRouteImport } from './routes/meus-direitos-lgpd'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CategoriaRouteImport } from './routes/$categoria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiPublicMerchantFeedRouteImport } from './routes/api/public/merchant/feed'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeReembolsoRoute = PoliticaDeReembolsoRouteImport.update({
  id: '/politica-de-reembolso',
  path: '/politica-de-reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusDireitosLgpdRoute = MeusDireitosLgpdRouteImport.update({
  id: '/meus-direitos-lgpd',
  path: '/meus-direitos-lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaRoute = CategoriaRouteImport.update({
  id: '/$categoria',
  path: '/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiPublicMerchantFeedRoute = ApiPublicMerchantFeedRouteImport.update({
  id: '/api/public/merchant/feed',
  path: '/api/public/merchant/feed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$categoria': typeof CategoriaRoute
  '/blog': typeof BlogRouteWithChildren
  '/busca': typeof BuscaRoute
  '/checkout': typeof CheckoutRoute
  '/meus-direitos-lgpd': typeof MeusDireitosLgpdRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-reembolso': typeof PoliticaDeReembolsoRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/merchant/feed': typeof ApiPublicMerchantFeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$categoria': typeof CategoriaRoute
  '/blog': typeof BlogRouteWithChildren
  '/busca': typeof BuscaRoute
  '/checkout': typeof CheckoutRoute
  '/meus-direitos-lgpd': typeof MeusDireitosLgpdRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-reembolso': typeof PoliticaDeReembolsoRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/merchant/feed': typeof ApiPublicMerchantFeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$categoria': typeof CategoriaRoute
  '/blog': typeof BlogRouteWithChildren
  '/busca': typeof BuscaRoute
  '/checkout': typeof CheckoutRoute
  '/meus-direitos-lgpd': typeof MeusDireitosLgpdRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-reembolso': typeof PoliticaDeReembolsoRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/merchant/feed': typeof ApiPublicMerchantFeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$categoria'
    | '/blog'
    | '/busca'
    | '/checkout'
    | '/meus-direitos-lgpd'
    | '/politica-de-privacidade'
    | '/politica-de-reembolso'
    | '/termos-de-uso'
    | '/blog/$slug'
    | '/produto/$slug'
    | '/api/public/merchant/feed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$categoria'
    | '/blog'
    | '/busca'
    | '/checkout'
    | '/meus-direitos-lgpd'
    | '/politica-de-privacidade'
    | '/politica-de-reembolso'
    | '/termos-de-uso'
    | '/blog/$slug'
    | '/produto/$slug'
    | '/api/public/merchant/feed'
  id:
    | '__root__'
    | '/'
    | '/$categoria'
    | '/blog'
    | '/busca'
    | '/checkout'
    | '/meus-direitos-lgpd'
    | '/politica-de-privacidade'
    | '/politica-de-reembolso'
    | '/termos-de-uso'
    | '/blog/$slug'
    | '/produto/$slug'
    | '/api/public/merchant/feed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriaRoute: typeof CategoriaRoute
  BlogRoute: typeof BlogRouteWithChildren
  BuscaRoute: typeof BuscaRoute
  CheckoutRoute: typeof CheckoutRoute
  MeusDireitosLgpdRoute: typeof MeusDireitosLgpdRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PoliticaDeReembolsoRoute: typeof PoliticaDeReembolsoRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicMerchantFeedRoute: typeof ApiPublicMerchantFeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-reembolso': {
      id: '/politica-de-reembolso'
      path: '/politica-de-reembolso'
      fullPath: '/politica-de-reembolso'
      preLoaderRoute: typeof PoliticaDeReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-direitos-lgpd': {
      id: '/meus-direitos-lgpd'
      path: '/meus-direitos-lgpd'
      fullPath: '/meus-direitos-lgpd'
      preLoaderRoute: typeof MeusDireitosLgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$categoria': {
      id: '/$categoria'
      path: '/$categoria'
      fullPath: '/$categoria'
      preLoaderRoute: typeof CategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/public/merchant/feed': {
      id: '/api/public/merchant/feed'
      path: '/api/public/merchant/feed'
      fullPath: '/api/public/merchant/feed'
      preLoaderRoute: typeof ApiPublicMerchantFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriaRoute: CategoriaRoute,
  BlogRoute: BlogRouteWithChildren,
  BuscaRoute: BuscaRoute,
  CheckoutRoute: CheckoutRoute,
  MeusDireitosLgpdRoute: MeusDireitosLgpdRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PoliticaDeReembolsoRoute: PoliticaDeReembolsoRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicMerchantFeedRoute: ApiPublicMerchantFeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
